version: '3.8'

services:
  suwayomi:
    image: ghcr.io/suwayomi/suwayomi-server:v2.2.2221-preview
    container_name: suwayomi
    ports:
      - "4567:4567"
    volumes:
      - ./suwayomi-data:/home/suwayomi/.local/share/Tachidesk
    restart: unless-stopped

